var annotated_dup =
[
    [ "gamepos", "namespacegamepos.html", [
      [ "GamePos", "structgamepos_1_1_game_pos.html", "structgamepos_1_1_game_pos" ]
    ] ],
    [ "pgn_impl", "namespacepgn__impl.html", [
      [ "InputMemory", "classpgn__impl_1_1_input_memory.html", "classpgn__impl_1_1_input_memory" ]
    ] ],
    [ "ByteBuffer", "class_byte_buffer.html", "class_byte_buffer" ],
    [ "CachedFilter", "struct_cached_filter.html", "struct_cached_filter" ],
    [ "ChessBase", "class_chess_base.html", "class_chess_base" ],
    [ "CodecMemory", "class_codec_memory.html", "class_codec_memory" ],
    [ "CodecPgn", "class_codec_pgn.html", "class_codec_pgn" ],
    [ "CodecProxy", "class_codec_proxy.html", "class_codec_proxy" ],
    [ "CodecSCID4", "class_codec_s_c_i_d4.html", "class_codec_s_c_i_d4" ],
    [ "CodecSCID5", "class_codec_s_c_i_d5.html", "class_codec_s_c_i_d5" ],
    [ "CompressedFilter", "class_compressed_filter.html", "class_compressed_filter" ],
    [ "DString", "class_d_string.html", "class_d_string" ],
    [ "FastBoard", "class_fast_board.html", "class_fast_board" ],
    [ "Filebuf", "class_filebuf.html", "class_filebuf" ],
    [ "FilebufAppend", "class_filebuf_append.html", "class_filebuf_append" ],
    [ "Filter", "class_filter.html", "class_filter" ],
    [ "FullMove", "class_full_move.html", "class_full_move" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameView", "class_game_view.html", "class_game_view" ],
    [ "HashVal", "class_hash_val.html", "class_hash_val" ],
    [ "HFilter", "class_h_filter.html", "class_h_filter" ],
    [ "HFilterInverted", "class_h_filter_inverted.html", "class_h_filter_inverted" ],
    [ "htmlStyleT", "structhtml_style_t.html", "structhtml_style_t" ],
    [ "ICodecDatabase", "class_i_codec_database.html", "class_i_codec_database" ],
    [ "Impl", "struct_impl.html", "struct_impl" ],
    [ "Index", "class_index.html", "class_index" ],
    [ "IndexEntry", "class_index_entry.html", "class_index_entry" ],
    [ "MaterialCount", "class_material_count.html", "class_material_count" ],
    [ "MoveList", "class_move_list.html", "class_move_list" ],
    [ "moveT", "structmove_t.html", "structmove_t" ],
    [ "NameBase", "class_name_base.html", "class_name_base" ],
    [ "OldProgress", "class_old_progress.html", "class_old_progress" ],
    [ "patternT", "structpattern_t.html", "structpattern_t" ],
    [ "PgnParseLog", "struct_pgn_parse_log.html", "struct_pgn_parse_log" ],
    [ "PgnVisitor", "class_pgn_visitor.html", "class_pgn_visitor" ],
    [ "PieceFromByte", "class_piece_from_byte.html", "class_piece_from_byte" ],
    [ "PieceList", "class_piece_list.html", "class_piece_list" ],
    [ "Position", "class_position.html", "class_position" ],
    [ "Progress", "class_progress.html", "class_progress" ],
    [ "ProgressImpl", "class_progress_impl.html", "class_progress_impl" ],
    [ "scidBaseT", "structscid_base_t.html", "structscid_base_t" ],
    [ "ScoredMove", "struct_scored_move.html", "struct_scored_move" ],
    [ "SearchTournaments", "class_search_tournaments.html", "class_search_tournaments" ],
    [ "simpleMoveT", "structsimple_move_t.html", "structsimple_move_t" ],
    [ "SortCache", "class_sort_cache.html", "class_sort_cache" ],
    [ "sqDir_Init", "structsq_dir___init.html", "structsq_dir___init" ],
    [ "SquareList", "class_square_list.html", "class_square_list" ],
    [ "SquareSet", "class_square_set.html", "class_square_set" ],
    [ "StoredLine", "class_stored_line.html", "class_stored_line" ],
    [ "StrRange", "class_str_range.html", "class_str_range" ],
    [ "TagRoster", "struct_tag_roster.html", "struct_tag_roster" ],
    [ "TextBuffer", "class_text_buffer.html", "class_text_buffer" ],
    [ "Tourney", "class_tourney.html", "class_tourney" ],
    [ "TourneyGame", "struct_tourney_game.html", "struct_tourney_game" ],
    [ "TreeCache", "class_tree_cache.html", "class_tree_cache" ],
    [ "TreeNode", "struct_tree_node.html", "struct_tree_node" ],
    [ "UndoRedo", "class_undo_redo.html", "class_undo_redo" ],
    [ "VectorChunked", "class_vector_chunked.html", "class_vector_chunked" ]
];