name: Generate Doxygen Docs

on:
  push:
    branches:
      - main  # Déclenche l'action lors de modifications sur la branche main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Doxygen
      - name: Install Doxygen Graphviz
        run: sudo apt-get install -y doxygen graphviz

      # 3. Generate Doxygen documentation
      - name: Generate docs
        run: doxygen Doxyfile

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Doxygen/html

